// AUTO-GÉNÉRÉ depuis test/public/js/app.js (ancienne version PHP) — ne pas éditer à la main.
// Régénérer : node scripts/extract-legacy-icons.cjs

export type IconCategory = { label: string; icons: string[] };

export const ICON_CATEGORIES: IconCategory[] = [
  {
    label: "Sport & Mouvement",
    icons: [
      "🏃",
      "🏋️",
      "🤸",
      "🚴",
      "⛹️",
      "🧘",
      "💃",
      "🕺",
      "🏊",
      "🤽",
      "⚽",
      "🏀",
      "🎾",
      "🏸",
      "🎿",
      "🏄",
      "🤾",
      "🏐",
    ],
  },
  {
    label: "Musique",
    icons: ["🎵", "🎶", "🎼", "🎸", "🎹", "🎺", "🎻", "🥁", "🎤", "🎙️", "🎧", "🪗", "🪘", "🪕"],
  },
  {
    label: "Arts & Création",
    icons: ["🎨", "🖌️", "✏️", "🖊️", "🖼️", "🗿", "🏺", "✂️", "📐", "🧵", "🪡", "🧶", "🖶"],
  },
  { label: "Scène & Spectacle", icons: ["🎭", "🎬", "🎪", "🎠", "🤹", "🎟️", "🎞️"] },
  { label: "Cuisine", icons: ["🍳", "👨‍🍳", "🥐", "🍰", "🧁", "🫕", "🥘", "🍽️", "🧑‍🍳"] },
  { label: "Photo & Vidéo", icons: ["📷", "📸", "🤳", "🎥", "🎞️", "📹"] },
  { label: "Numérique", icons: ["💻", "🖥️", "⌨️", "🖱️", "🤖", "⚙️", "📱"] },
  { label: "Langues & Lecture", icons: ["📖", "📚", "📕", "🔖", "🌍", "🗣️", "✍️", "📝"] },
  { label: "Nature & Jardin", icons: ["🌱", "🌻", "🪴", "🌿", "🌳", "🍃", "♻️", "🌸", "🌺", "🦋"] },
  { label: "Culture & Patrimoine", icons: ["🏛️", "🗺️", "🎫", "🔭", "🏺", "⛪", "🏰", "🗽"] },
  { label: "Sciences & Atelier", icons: ["🔬", "🧪", "⚗️", "🔧", "🛠️", "🧰", "💡", "🧲", "🔩"] },
  {
    label: "Enfance",
    icons: [
      "🧸",
      "🪀",
      "🪁",
      "🎠",
      "🎡",
      "🎢",
      "🎪",
      "🎈",
      "🎉",
      "🪄",
      "🧩",
      "🎮",
      "🪆",
      "🏰",
      "🌈",
      "🧁",
      "🍭",
      "🦄",
      "🐣",
      "🐥",
    ],
  },
  {
    label: "Bâtiments",
    icons: [
      "🏛️",
      "🏰",
      "🏯",
      "⛪",
      "🕌",
      "🕍",
      "🛕",
      "🏗️",
      "🏢",
      "🏬",
      "🏪",
      "🏫",
      "🏩",
      "🏥",
      "🏦",
      "🏨",
      "🏤",
      "🏣",
      "🏟️",
      "🗼",
      "🗽",
      "🗿",
      "⛩️",
      "🏠",
      "🏡",
      "🏚️",
    ],
  },
  {
    label: "Divers",
    icons: [
      "📌",
      "🎯",
      "⭐",
      "🔷",
      "🏷️",
      "📋",
      "🎗️",
      "🧩",
      "🔑",
      "🌈",
      "🎁",
      "🏆",
      "🥇",
      "❤️",
      "✨",
      "🔔",
    ],
  },
];
